In [1]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris

In [2]:
iris = load_iris()                 # sklearn's Bunch class form
iris                               # at the end of the loaded data(scroll down), there is the path for the csv file.

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
# loading the csv file format
test = pd.read_csv("C:\\Users\\pc\\Anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\iris.csv")
test.head()

150    4  setosa  versicolor  virginica
0  5.1  3.5     1.4         0.2          0
1  4.9  3.0     1.4         0.2          0
2  4.7  3.2     1.3         0.2          0
3  4.6  3.1     1.5         0.2          0
4  5.0  3.6     1.4         0.2          0

In [4]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [5]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [6]:
# assigning the columns as the features_names
test.columns = ['sepal length','sepal width','petal length','petal width','species']
test.head(3)

sepal length  sepal width  petal length  petal width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0

In [7]:
# spliting train and test data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(test.drop(["species"], axis=1),
                                                    test['species'], test_size=0.3, random_state=0)

In [8]:
# checking the shape for each element
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((105, 4), (45, 4), (105,), (45,))

In [9]:
# import KNN classification model
from sklearn.neighbors import KNeighborsClassifier

# fit the model on the training set with 1 neighbors
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=1, p=2,
           weights='uniform')

In [10]:
# check the accuracy for the train and test data
round(knn.score(X_test, y_test), 2), round(knn.score(X_train, y_train), 2)

(0.98, 1.0)

In [11]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# predict the values for the test set
y_pred = knn.predict(X_test)
print(y_pred[:10])

# calculate the accuracy about the predicted result
print("Accuracy:", accuracy_score(y_test, y_pred))

# report for other classification measures
print("Classification report:")
print(classification_report(y_test, y_pred))

# and the confusion matrix
print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred))

[2 1 0 2 0 2 0 1 1 1]
Accuracy: 0.9777777777777777
Classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

   micro avg       0.98      0.98      0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

Confusion matrix:
[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]


In [12]:
# check the predicted result in the 'species' column
X_test['species']=y_pred
X_test.head(3)

sepal length  sepal width  petal length  petal width  species
114           5.8          2.8           5.1          2.4        2
62            6.0          2.2           4.0          1.0        1
33            5.5          4.2           1.4          0.2        0

In [13]:
# check the result as the converted target name
X_test['name']=X_test.species.replace({0 : "setosa", 1: 'versicolor', 2: 'virginica' })
X_test.head()

sepal length  sepal width  petal length  petal width  species        name
114           5.8          2.8           5.1          2.4        2   virginica
62            6.0          2.2           4.0          1.0        1  versicolor
33            5.5          4.2           1.4          0.2        0      setosa
107           7.3          2.9           6.3          1.8        2   virginica
7             5.0          3.4           1.5          0.2        0      setosa